[T1451] - Fix: Muskathlon event ambassador
CompassionCH/compassion-website pull request #16
Opened 2024-06-19 11:00 UTC by langjer

Event ambassador was rewritten by crowdfunding, context was constantly rewrite and I didn't find a way to pass it correctly. So I use another way, working as well. Parameters are unique for each module, crowdfunding (by using participant_id) and event (by using registration_id). In any case, one of them will be null.

2024-06-19 13:08 UTC, NoeBerdoz commented on website_event_compassion/models/sale_order_line.py
> +            analytic = self.registration_id.compassion_event_id.analytic_id
Would be better to set all in one the dictionary values instead of just analytic for a cleaner structure
```suggestion
           user_id = self.registration_id.partner_id.id
            analytic_id = self.registration_id.compassion_event_id.analytic_id.id
            
            res.update({
                "user_id": user_id,
                "analytic_account_id": analytic_id,
            })
```
But as it is a hotfix, i wonder how important it is to make it clean...
(same case in crowdfunding changes)

2024-06-20 06:37 UTC, ecino requested changes
Looks good, only cosmetic changes.

2024-06-20 06:37 UTC, ecino commented on crowdfunding_compassion/models/sale_order_line.py
> +            )
Cosmetic changes to reduce the number of lines.
```suggestion
        participant = getattr(self, 'participant_id', False)
        if participant:
            res.update(
                {
                    "user_id": participant.partner_id.id,
                    "analytic_account_id": participant.project_id.event_id.analytic_id.id,
                    "crowdfunding_participant_id": participant.id,
                }
            )
```

2024-06-20 06:37 UTC, ecino commented on website_event_compassion/models/sale_order_line.py
> +            )
```suggestion
        res = super()._prepare_invoice_line(**optional_values)
        registration = getattr(self, 'registration_id', False)
        if registration: 
            res.update(
                {
                    "user_id": registration.partner_id.id,
                    "analytic_account_id": registration.compassion_event_id.analytic_id.id,
                }
            )
```

2024-06-20 07:18 UTC, ecino approved these changes

2024-06-20 07:19 UTC, merged