[T1906] FEAT: Add new MyCompassion user signup logic using OCA module 2/2
CompassionCH/compassion-website pull request #55
Opened 2024-11-29 14:49 UTC by robinrolle

Adding the new signup for MyCompassion.

This solution use the OCA module "auth_signup_verify_email" from https://github.com/OCA/server-auth/tree/14.0

The two main objectives were:

- Sending a confirmation email to the newly signed-up user to activate their account.
- Linking the new user to a potentially existing partner based on the email address provided during signup.

The partner is selected based on the number of sponsorships, and in case of a tie, the most recently updated partner is chosen.

Partner linking is handled asynchronously. By default, a new partner is created as usual. If an existing partner is found, the res_user and res_partner data are updated to establish the link."

2024-12-03 13:29 UTC, ecino requested changes
Please check my comments. You can also bring in the modifications you did inside the `partner_communication_compassion` module.

2024-12-03 13:29 UTC, ecino commented on my_compassion/models/res_user.py
> +        values.pop("privacy_policy", None)
Where does this come from?

2024-12-03 13:29 UTC, ecino commented on my_compassion/models/res_user.py
> +                partner_user._notify_inviter()
Can't we use the super() call in this case? It's a better practice rather than re-writing existing code.

2024-12-03 13:29 UTC, ecino commented on my_compassion/models/res_user.py
> +        """create signup token for each user, and send their signup url by email"""
I don't understand why we need to redefine the reset password action? Isn't the parent process working as needed?

2024-12-05 08:55 UTC, robinrolle commented
- Called super() method  for res_user signup
- Included template and communication config in this module

It is necessary to redefine action_reset_password, because we want to create a communication job instead of sending directly a mail.

2024-12-09 07:17 UTC, ecino requested changes

2024-12-09 07:17 UTC, ecino commented on my_compassion/data/signup_email_confirmation.xml
> +    </tr>
We don't need this footer. We have a custom signature.
```suggestion
```

2024-12-09 07:17 UTC, ecino commented on my_compassion/data/signup_email_confirmation.xml
> +            </field>
```suggestion
</table>
${object.user_id.signature | safe}
            </field>
```

2024-12-09 07:17 UTC, ecino commented on my_compassion/models/res_user.py
> +                ) from e
We already [redefined this method here](https://github.com/CompassionCH/compassion-switzerland/blob/14.0/partner_communication_switzerland/models/res_users.py#L21), are you sure we need it here?

2024-12-12 13:22 UTC, robinrolle commented
As discussed

### Kept action_reset_password override
Although the method name is misleading, it handles user account creation. The new method only applies to user creation and does not interfere with the existing password reset flow.

### Fixed Double Email Issue
Resolved duplicate email sending caused by the email configuration (Default recipients).

### Updated Email Template
Modified the template to align with the style of existing email templates.

2024-12-12 14:51 UTC, ecino approved these changes

2024-12-19 08:31 UTC, merged